### ISSUE TITLE
TGPDiscreteSlider: Tint colour sets the track colour, rather than the 'fill' color

### ISSUE THREAD

**Issue by fatuhoku** [SwiftArchitect/TGPControls#10]
Thanks for this component. The discrete notches work really well.

Issue: I set the `tintColor` in IB, thinking it'd change the default iOS blueish colour. It actually set the colour of the remainder of the track instead.

![screen shot 2015-08-13 at 16 13 04](https://cloud.githubusercontent.com/assets/430233/9253543/354abe18-41d6-11e5-99e6-e79750dd3f06.png)

To me, `tintColor` should be the fill colour, and the track colour should remain greyish by default.

**Comment by fatuhoku** [comment]
Better still, I expect that `TGPDiscreteSlider` should adopt the `minumum/maximumTrackTintColor` properties in `UISlider`.

**Comment by SwiftArchitect** [comment]
Do you have a fix for this issue ; if not, I can release a new version.

**Comment by fatuhoku** [comment]
@SwiftArchitect Sorry no fix — please go ahead!

**Comment by SwiftArchitect** [comment]
This requires an API and behavior change. Will be available in TGPControls 2.0.
