### ISSUE TITLE
TGPCamelLabel.ticksDistance is not same as TGPDiscreteSlider.ticksDistance

### ISSUE THREAD

**Issue by shrutic** [SwiftArchitect/TGPControls#11]
As per the read me, I did the following to ensure that the label appears correctly above the discrete slider ticks. 

camelLabel.ticksDistance = discreteSlider.ticksDistance

When I do that I get the following 
![ticks](https://cloud.githubusercontent.com/assets/4141641/9259272/f3232352-41b4-11e5-9405-10e23d752805.png)

Context:
1) Both the discreteSlider and the camelLabel are created in storyboard by changing the class of UIView to the TGPDiscreteSlider and TGPCamelLabel respectively. 
2) Installed the TGPControls via CocoaPods
3) Using Xcode 6.4 , iOS 8, Swift 1.2
4) The tick labels are assigned in viewDidLoad as ["0", "1" ... "10"] . As you can notice 1, 9 and 10 are rendering outside the screen. The screenshot is on iPhone 6 Plus actual device 
5) The TGPDiscreteSlider and the TGPCamelLabel have the trailing to super view trailing and leading to superview.leading set to 0. ( basically the constraints ask it to occupy the width of the device

Would appreciate if you could guide me on what I am doing incorrectly

**Comment by shrutic** [comment]
Looking at the closed issues, I figured I can assign the tickDistance automatically by assigning the labels to listen to the slider

discreteSlider.listener = camelLabel.

This fixed the above issue for me. But the issue still exists that manually assigning the distance does not work

**Comment by SwiftArchitect** [comment]
Excellent comment. I will look into an easier method to do this. It is definitely problematic, since labels must adjust to the slider ticks which are subject to change dynamically.

**Comment by SwiftArchitect** [comment]
*Works as designed.*

The key is to invoke `label.ticksDistance = slider.ticksDistance` **after** the `TGPSlider` view has been laid out, such as in `viewDidAppear()`, as opposed to `viewDidLoad()`.

    // Logged during viewDidLoad()
    self.alphabetSlider.ticksDistance = 13.12
    // Logged during viewDidAppear()
    self.alphabetSlider.ticksDistance = 10.92

----

Using the `ticksListener` mechanism is not subject to that limitation, because the `TGPSlider` is able to communicate the correct `ticksDistance` to the `TGPCamelLabel` dynamically, even if you tie the two together in `viewDidLoad()`.

I have clarified the documentation.
