### ISSUE TITLE
TGPDiscreteSlider does not seem to fire TouchDragExit events for me to know when user took hand away from slider

### ISSUE THREAD

**Issue by shrutic** [SwiftArchitect/TGPControls#13]
I tried adding a TouchUp target for the TGPDiscreteSlider
        self.discreteSlider.addTarget(self, action: "discreteSliderTouchUp:", forControlEvents: .TouchUpOutside | .TouchUpInside)

But the selector never gets called. 
Could you let me know how I can detect if user has finished sliding on the TGPDiscreteSlider?

**Comment by SwiftArchitect** [comment]
There is no easy way to do this in version 1.0.0.
The messages is trapped by `TGPDiscreteSlider7:touchUp` and is not broadcasted.

**Comment by SwiftArchitect** [comment]
This will be available in version 1.1.0.
