### ISSUE TITLE
setValue

### ISSUE THREAD

**Issue by mythodeia** [SwiftArchitect/TGPControls#14]
Hello and thanks for your library.
i have setup a TGPDiscreteSlider7 on my storyboard and i would like to change its value programmatically. Calling setValue on the control does not seem to do anything. The slider does not move. 
Am i missing something in the implementation in order to make it move programmatically?
thanks

EDIT:
calling setValue on your oneTo10Slider in the demo project works as expected.
calling setValue on either of the last 2 sliders in the demo project does not work and i have set them up as a property so i can call them

By the way...calling setValue on anywhere else than viewDidLoad even on the oneTo10Slider does not move it.

**Comment by mythodeia** [comment]
i think i have found the issue.
in order to move the slider programmatically using setValue i had to change the ```layoutTrack``` method and add ```[self setNeedsDisplay];``` at the end of it. now the slider moves at will

can anyone confirm this?

**Comment by SwiftArchitect** [comment]
Can you create a pull request?

**Comment by mythodeia** [comment]
:+1:

**Comment by SwiftArchitect** [comment]
Sorry for the long delay. This issue eluded my attention since the issue
was closed.
Is there anything else you have noticed that has not been reported?

Cheers,
Xavier

**Comment by mythodeia** [comment]
no worries. if i find anything else i will of course notify you! thanks for your time
