### ISSUE TITLE
Unrecognized Selector sent to Instance "DiscreteSlider" - Swift 3.0

### ISSUE THREAD

**Issue by liltimtim** [SwiftArchitect/TGPControls#18]
Get unrecognized selector when adding a target to TGPDiscreteSlider

anchorRatingSlider.addTarget(self, action: #selector(sliderAnchorRatingValueChange(_:)), for: .valueChanged)

Running Xcode 8 Swift 3.0

**Comment by SwiftArchitect** [comment]
##Swift 3

Use:

`dualColorSlider.addTarget(self, action: #selector(sliderAnchorRatingValueChange(_:)), for: .valueChanged)`

 with method signature:

`func sliderAnchorRatingValueChange(_ sender: TGPDiscreteSlider)`

and:

`dualColorSlider.addTarget(self, action: #selector(sliderAnchorRatingValueChange(_:event:)), for: .valueChanged)`

 with method signature:

`func sliderAnchorRatingValueChange(_ sender: TGPDiscreteSlider, event:UIEvent)`
