### ISSUE TITLE
Use of undeclared type 'TGPDiscreteSlide'

### ISSUE THREAD

**Issue by lindseyvastola** [SwiftArchitect/TGPControls#42]
I have imported the TGPControls framework to my app, added these imports to the top of my swift controller:
import UIKit
import TGPControls

but I get undeclared type when I try to create the object. 
@IBOutlet weak var discreteSlider: TGPDiscreteSlide!

What am I doing wrong?

**Comment by SwiftArchitect** [comment]
Probably a typo:
`@IBOutlet weak var discreteSlider: TGPDiscreteSlider!`
